### ISSUE TITLE
?

### ISSUE THREAD

**Issue by BLOCKSTORMPE** [HGHD-Developer/Report-ZeroTouch-Edition#1]
Kann es sein dass dieses Plugin nicht von dir ist? Dass du in deinem Plugin das Wort Motivo verwendest, weist darauf hin dass der src aus einem Spanischen Plugin kommt. Ich vermute mal du hast teile von Bluplayz Plugin verwendet...
Wenn ja, dann gib bitte auf Credits.
Und Außerdem:
WIESO SOLL DAS BITTE MIT GOMINT GEHEN?!
GoMint ist Java und das ist ein plugin PHP! Verarschen kann ich mich alleine, bitte ändern...

**Comment by HGHD-Developer** [comment]
Das nit gomint habe ich irgendwie verkackt, ich weiß... allerdings ist die src von mir aber wenn du das meinst das es von jmd anderem ist dann ist das ok. Meinungsfreiheit... wäre damit alles geklärt?
